name: My First Workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: Welcome message
      run: echo "my first Workflow"

    - name: Fetching files name from the repository
      run: ls
    
    - name: Read files
      run: cat README.md

