name: Matrix configuration

on:
    push:
    workflow_dispatch: 
jobs:
    deploy:
        strategy:
            matrix:
                runs-on: [ubuntu-latest, windows-latest]
                imags: [hello-world, alpine] 
        runs-on: ${{ matrix.runs-on }}
        steps:
        -   name: Echo Docker details
            run: docker info
            
        -   name: Run Images
            run: docker run ${{ matrix.imags }}
 